# Generated by Django 3.2 on 2023-04-18 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230417_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('pace', models.CharField(blank=True, help_text='The pace of the running session as HH:MM:SS.', max_length=50, null=True)),
                ('day', models.CharField(blank=True, max_length=50, null=True)),
                ('task_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('train_pref', models.ManyToManyField(blank=True, to='api.TrainingPreference')),
            ],
        ),
        migrations.DeleteModel(
            name='DailyTask',
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='daily_task',
            field=models.ManyToManyField(blank=True, to='api.DailyTasks'),
        ),
    ]
