# Generated by Django 3.2 on 2023-04-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230418_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingschedule',
            name='workout',
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='friday_workout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='monday_workout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='saturday_workout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='sunday_workout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='thursday_workout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='tuesday_workout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='wednesday_workout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
