# Generated by Django 3.2 on 2023-04-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230418_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingschedule',
            name='is_achieved',
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='is_complete_friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='is_complete_monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='is_complete_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='is_complete_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='is_complete_thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='is_complete_tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='is_complete_wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
