# Generated by Django 3.2 on 2023-04-18 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230418_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingschedule',
            name='train_pref',
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='train_pref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trainingpreference'),
        ),
    ]
