# Generated by Django 3.2 on 2023-04-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230418_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingschedule',
            name='monday_pace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='sunday_pace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
